[kijanikiosk]
api ansible_host=16.171.57.219
payments ansible_host=16.16.215.210
logs ansible_host=16.170.141.72

[kijanikiosk:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/sheila/.ssh/kijani-key.pem
